# Generated by Django 5.2.6 on 2025-09-11 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_news_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.TextField(db_column='content'),
        ),
        migrations.AlterField(
            model_name='news',
            name='name',
            field=models.CharField(db_column='title', max_length=255),
        ),
    ]
