# Generated by Django 5.2.6 on 2025-09-11 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_news_description_alter_news_name'),
    ]

    operations = [
        migrations.RunSQL(
            sql='ALTER TABLE "main_news" RENAME COLUMN "title" TO "name";',
            reverse_sql='ALTER TABLE "main_news" RENAME COLUMN "name" TO "title";',
        ),
        migrations.RunSQL(
            sql='ALTER TABLE "main_news" RENAME COLUMN "content" TO "description";',
            reverse_sql='ALTER TABLE "main_news" RENAME COLUMN "description" TO "content";',
        ),
    ]
