# Generated by Django 5.2.6 on 2025-09-11 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_title_to_name'),
    ]

    operations = [
        migrations.RunSQL(
            sql='ALTER TABLE "main_news" ADD COLUMN IF NOT EXISTS "price" integer NOT NULL DEFAULT 0;',
            reverse_sql='ALTER TABLE "main_news" DROP COLUMN IF EXISTS "price";',
        ),
        # (opsional) kalau tak ingin default 0 bertahan:
        migrations.RunSQL(
            sql='ALTER TABLE "main_news" ALTER COLUMN "price" DROP DEFAULT;',
            reverse_sql='ALTER TABLE "main_news" ALTER COLUMN "price" SET DEFAULT 0;',
        ),
    ]
