# main/migrations/0006_add_price_column.py
# Generated by Django 5.2.6 on 2025-09-11 22:35

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_title_to_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='price',
            # sesuai niat awal kamu (integer + default 0)
            field=models.IntegerField(default=0),
        ),
    ]
