# Generated by Django 5.2.6 on 2025-09-22 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_news_user_alter_news_description_alter_news_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='price',
            field=models.IntegerField(),
        ),
    ]
